CREATE TABLE login (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL
);

CREATE TABLE ramen_reviews (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    STORE_NAME VARCHAR(100) NOT NULL,
    COMMENT TEXT NOT NULL,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES login(ID)
);