CREATE TABLE login (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL
);

CREATE TABLE ramen_reviews (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    STORE_NAME VARCHAR(100) NOT NULL,
    COMMENT TEXT NOT NULL,
    TASTE_ID INT NOT NULL,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES login(ID),
    FOREIGN KEY (TASTE_ID) REFERENCES taste(ID)
);

CREATE TABLE taste (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

INSERT INTO taste (NAME) VALUES
('醤油'),
('味噌'),
('豚骨'),
('家系'),
('その他');